# Generated by Django 2.2.4 on 2022-03-24 01:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('currentPower', models.SmallIntegerField(verbose_name='Current power')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_device', to='device.Device')),
                ('typeDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_typeDevice', to='device.TypeDevice')),
            ],
            options={
                'verbose_name_plural': 'Readings',
                'db_table': 'readings',
            },
        ),
    ]
